pgn: Replace getopts with getopt

diff --git a/find/find b/find/find
--- a/find/find
+++ b/find/find
@@ -1,30 +1,10 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-CONF=
-
-PRJ=
-ID=
-BASE=
-CMD=
-
-while getopts "B:p:i:s" opt; do
-    case "${opt}" in
-        B)
-            BASE="$OPTARG"
-            ;;
-        p)
-            PRJ="$OPTARG"
-            ;;
-        i)
-            ID="$OPTARG"
-            ;;
-        *)
-            exit 1
-    esac
-done
-
-shift $((OPTIND-1))
-CMD="$1"
+PGNAME="find"
+PATTERN=
+TASKDIR=
+PRJNAME=
+TASKNAME=
 
 function usage()
 {
@@ -33,31 +13,61 @@ Usage: tman find [OPTION]... PATTERN
     Find items in database.
 
     Options:
-      -i    find task ID by PATTERN
-      -b    find board name by PATTERN
-      -p    find project name by PATTERN
+      -i    find task ID by PATTERN (under development)
+      -b    find board name by PATTERN  (under development)
+      -p    find project name by PATTERN (under development)
 EOF
 }
 
-function _find_config()
-{
-    local confdir=("$HOME/.tman/pgns/struct.conf" "$HOME/.config/tman/pgns/struct.conf")
 
-    for conf in "${confdir[@]}"; do
-        if [ -f "$conf" ]; then
-            CONF="$conf"
-            return 0
-        fi
-    done
-    return 1
-}
-
-
-_find_config && source "$CONF" || exit 0
-
-if [ "$CMD" == "help" ]; then
-    usage
-else
-    echo "no such command or empty '$CMD'"
+OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
+if [ $? -ne 0 ]; then
+    #echo "error parsing options" >&2
     exit 1
 fi
+
+## Reset the positional parameters to the parsed options
+eval set -- "$OPTS"
+
+while true; do
+    case "$1" in
+        -i)
+            TASKNAME="$2"
+            shift 2
+            ;;
+        -p)
+            PRJNAME="$2"
+            shift 2
+            ;;
+        -T)
+            TASKDIR="$2"
+            shift 2
+            ;;
+        -h)
+            usage
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "$PGNAME: invalid option '$1'" >&2
+            exit 1
+    esac
+done
+
+PATTERN="$1"
+if [ -z "$PATTERN" ]; then
+    echo "${PGNAME}: no pattern passed" >&2
+    exit 1
+fi
+
+for prj in $(ls "$TASKDIR"); do
+    find "$TASKDIR/$prj" -maxdepth 1 -name "*${PATTERN}*" | while read -r res; do
+        res="${res/$TASKDIR\//}"
+        PRJ="$(echo "$res" | cut -f 1 -d '/')"
+        ID="$(echo "$res" | cut -f 2 -d '/')"
+        echo "$PRJ - $ID"
+    done
+done
diff --git a/gun/gun b/gun/gun
--- a/gun/gun
+++ b/gun/gun
@@ -1,39 +1,56 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-CONF=
+# Dumb wrapper so a plugin can call its libraries
 
-PRJ=
-ID=
-BASE=
-CMD=
+PGNAME="gun"
+COMMAND=
+TASKDIR=
+PRJNAME=
+TASKNAME=
 
-while getopts "T:p:i:s" opt; do
-    case "${opt}" in
-        T)
-            BASE="$OPTARG"
+OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
+if [ $? -ne 0 ]; then
+    #echo "error parsing options" >&2
+    exit 1
+fi
+
+## Reset the positional parameters to the parsed options
+eval set -- "$OPTS"
+
+while true; do
+    case "$1" in
+        -i)
+            TASKNAME="$2"
+            shift 2
             ;;
-        p)
-            PRJ="$OPTARG"
+        -p)
+            PRJNAME="$2"
+            shift 2
             ;;
-        i)
-            ID="$OPTARG"
+        -T)
+            TASKDIR="$2"
+            shift 2
+            ;;
+        --)
+            shift
+            break
             ;;
         *)
-            echo "error: invalid option"
+            echo "$PGNAME: invalid option '$1'" >&2
             exit 1
-            ;;
     esac
 done
 
-shift $((OPTIND-1))
-CMD="$1"
+COMMAND="$1"
 
+if [ -z "$COMMAND" ]; then
+    echo "$PGNAME: no command passed"
+    exit 1
+fi
 
-# Dumb wrapper so a plugin can call its libraries
-[ -z "$CMD" ] && CMD="sync"
 CWD="$(pwd)"
 PGNDIR="`dirname $0`"
 
 cd "$PGNDIR" || exit 1
-lua gun.lua -p "$PRJ" -T "$BASE" -i "$ID" "$CMD"
+lua gun.lua -p "$PRJNAME" -T "$TASKDIR" -i "$TASKNAME" "$COMMAND"
 cd "$CWD" || exit 1
diff --git a/struct/struct b/struct/struct
--- a/struct/struct
+++ b/struct/struct
@@ -1,30 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-CONF=
+PGNAME="struct"
 
-PRJ=
-ID=
-BASE=
-CMD=
+COMMAND=
+TASKDIR=
+PRJNAME=
+TASKNAME=
 
-while getopts "T:p:i:s" opt; do
-    case "${opt}" in
-        T)
-            BASE="$OPTARG"
-            ;;
-        p)
-            PRJ="$OPTARG"
-            ;;
-        i)
-            ID="$OPTARG"
-            ;;
-        *)
-            exit 1
-    esac
-done
-
-shift $((OPTIND-1))
-CMD="$1"
 
 function usage()
 {
@@ -53,7 +35,7 @@ function _find_config()
     return 1
 }
 
-function struct_create()
+function struct_make()
 {
     for dir in "${STRUCT_DIRS[@]}"; do
         mkdir -p "$BASE/$PRJ/$ID/$dir"
@@ -85,6 +67,7 @@ function struct_show()
     printf "\nFiles : "
     for file in "${STRUCT_FILES[@]}"; do
         printf "%s " "$file"
+    echo
     done
 }
 
@@ -95,18 +78,60 @@ function struct_rename()
 }
 
 
+OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
+if [ $? -ne 0 ]; then
+    #echo "error parsing options" >&2
+    exit 1
+fi
+
+## Reset the positional parameters to the parsed options
+eval set -- "$OPTS"
+
+while true; do
+    case "$1" in
+        -i)
+            TASKNAME="$2"
+            shift 2
+            ;;
+        -p)
+            PRJNAME="$2"
+            shift 2
+            ;;
+        -T)
+            TASKDIR="$2"
+            shift 2
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "$PGNAME: invalid option '$1'" >&2
+            exit 1
+    esac
+done
+
+COMMAND="$1"
+
+if [ -z "$COMMAND" ]; then
+    echo "$PGNAME: no command passed"
+    exit 1
+fi
+
+
+
 _find_config && source "$CONF" || exit 0
 
-if [ -z "$CMD" -o "$CMD" = "make" ]; then
-    struct_create
-elif [ "$CMD" = "delete" ]; then
+if [ -z "$COMMAND" -o "$COMMAND" = "make" ]; then
+    struct_make
+elif [ "$COMMAND" = "delete" ]; then
     struct_delete
-elif [ "$CMD" = "rename" ]; then
+elif [ "$COMMAND" = "rename" ]; then
     struct_rename
-elif [ "$CMD" = "show" ]; then
+elif [ "$COMMAND" = "show" ]; then
     struct_show
-elif [ "$CMD" = "help" ]; then
+elif [ "$COMMAND" = "help" ]; then
     usage
 else
-    echo "no such command '$CMD'" && exit 1
+    echo "no such command '$COMMAND'" && exit 1
 fi
diff --git a/time/time b/time/time
--- a/time/time
+++ b/time/time
@@ -1,45 +1,53 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-PGNAME="time"
-CONF=
-PRJ=
-ID=
-BASE=
-CMD=
+# Dumb wrapper so a plugin can call its libraries
 
-while getopts "T:p:i:" opt; do
-    case "${opt}" in
-        T)
-            BASE="$OPTARG"
+PGNAME="gun"
+COMMAND=
+TASKDIR=
+PRJNAME=
+TASKNAME=
+
+OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
+if [ $? -ne 0 ]; then
+    #echo "error parsing options" >&2
+    exit 1
+fi
+
+## Reset the positional parameters to the parsed options
+eval set -- "$OPTS"
+
+while true; do
+    case "$1" in
+        -i)
+            TASKNAME="$2"
+            shift 2
             ;;
-        p)
-            PRJ="$OPTARG"
+        -p)
+            PRJNAME="$2"
+            shift 2
             ;;
-        i)
-            ID="$OPTARG"
+        -T)
+            TASKDIR="$2"
+            shift 2
+            ;;
+        --)
+            shift
+            break
             ;;
         *)
-            echo "invalid option"
+            echo "$PGNAME: invalid option '$1'" >&2
             exit 1
-            ;;
     esac
 done
 
-shift $((OPTIND-1))
-CMD="$1"
+COMMAND="$1"
 
-function _find_config()
-{
-    local confdir=("$HOME/.tman/pgns/${PGNAME}.conf" "$HOME/.config/tman/pgns/${PGNAME}.conf")
+if [ -z "$COMMAND" ]; then
+    echo "$PGNAME: no command passed"
+    exit 1
+fi
 
-    for conf in "${confdir[@]}"; do
-        if [ -f "$conf" ]; then
-            CONF="$conf"
-            return 0
-        fi
-    done
-    return 1
-}
 
 
 function time_init()
@@ -72,16 +80,14 @@ function time_help()
 }
 
 
-_find_config && source "$CONF" || exit 0
-
-if [ -z "$CMD" -o "$CMD" = "sync" ]; then
+if [ -z "$COMMAND" -o "$COMMAND" = "sync" ]; then
     time_sync
-elif [ "$CMD" = "rsync" ]; then
+elif [ "$COMMAND" = "rsync" ]; then
     time_rsync
-elif [ "$CMD" = "show" ]; then
+elif [ "$COMMAND" = "show" ]; then
     time_show
-elif [ "$CMD" = "help" ]; then
+elif [ "$COMMAND" = "help" ]; then
     time_help
 else
-    echo "$PGNAME: no such command '$CMD'" && exit 1
+    echo "$PGNAME: no such command '$COMMAND'" && exit 1
 fi
